baseurl: /laixiong.github.io
permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name:
  email: 
  github: 
  music: 
  linkedin: 

# 站点信息
title:
description: My personal blog
url: http://laixiong.net
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: 
favicon: 

# disqus 设置
disqus:
  shortname: laixiong


# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
